#!/bin/bash

if [[ "$1" == "docker-cli-plugin-metadata" ]]; then
cat << HERE
{
     "SchemaVersion": "0.1.0",
     "Vendor": "https://github.com/SvenDowideit",
     "Version": "v0.1.0",
     "ShortDescription": "Bash based Docker cli-plugin"
}
HERE
exit
fi

echo "========================"
env
echo "========================"
echo $@
echo "========================"

